apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-example
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/lakkigithub/argocd.git
        revision: HEAD
        directories:
          - path: helm-nginx
          - path: nginx-deployment
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopshobbies/argocd-tutorial.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true