apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-generator-ex1
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://127.0.0.1:59764
            path: helm/nginx
          - cluster: default
            url: https://kubernetes.default.svc
            path: nginx-deployment
  template:
    metadata:
      name: '{{cluster}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopshobbies/argocd-tutorial.git
        targetRevision: main
        path: {{path}}
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true